name: ui_kit
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.0-36.0.dev

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: SfPro
      fonts:
        - asset: fonts/SF-Pro-Display-Regular.otf
        - asset: fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: fonts/SF-Pro-Display-Bold.otf
          weight: 700
        - asset: fonts/SF-Pro-Display-Heavy.otf
          weight: 800

    - family: ArticleIcons
      fonts:
        - asset: fonts/Article-icons.otf
