// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPliY6nqKHo4JOsXOGHWxNFTT6n6hSR-I',
    appId: '1:1031256898634:android:d3f74c994a2ce8e9bdbab3',
    messagingSenderId: '1031256898634',
    projectId: 'article-b3280',
    storageBucket: 'article-b3280.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkfABqeG5s7rOzarYEpQybd_JuHHO0mR4',
    appId: '1:1031256898634:ios:b7a749b37259b99bbdbab3',
    messagingSenderId: '1031256898634',
    projectId: 'article-b3280',
    storageBucket: 'article-b3280.firebasestorage.app',
    iosBundleId: 'com.example.arcticleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkfABqeG5s7rOzarYEpQybd_JuHHO0mR4',
    appId: '1:1031256898634:ios:b7a749b37259b99bbdbab3',
    messagingSenderId: '1031256898634',
    projectId: 'article-b3280',
    storageBucket: 'article-b3280.firebasestorage.app',
    iosBundleId: 'com.example.arcticleApp',
  );

}